# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-25 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20160406_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='created_date',
            new_name='created_date_temp',
        ),
    ]
