# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-25 03:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20180124_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
