# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-25 18:03
from __future__ import unicode_literals
from datetime import datetime

from django.db import migrations


def not_null_expiration_date(apps, schema_editor):
    '''This provides a value to all null expiration_date values in Menu.'''
    Menu = apps.get_model('menu', 'Menu')
    for menu in Menu.objects.all():
        if menu.expiration_date is None:
            menu.expiration_date = datetime(2014, 8, 18)
            menu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_item_created_date_temp'),
    ]

    operations = [
        migrations.RunPython(not_null_expiration_date)
    ]
