# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-25 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20180125_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='expiration_date',
            new_name='expiration_date_temp',
        ),
    ]
