# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-25 18:25
from __future__ import unicode_literals

from django.db import migrations


def expiration_date_temp_to_expiration_date(apps, schema_editor):
    '''This copys the expiration_date_temp data to expiration_date.'''
    Menu = apps.get_model('menu', 'Menu')
    for menu in Menu.objects.all():
        menu.expiration_date = menu.expiration_date_temp.date()
        menu.save()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menu_expiration_date'),
    ]

    operations = [
        migrations.RunPython(expiration_date_temp_to_expiration_date)
    ]
