# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-01-25 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_auto_20180125_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='expiration_date_temp',
        ),
    ]
